---
#
# Open edX Mongo-pruner Pipeline Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Deploy the Mongo-pruner Pipeline
#
# See documentation in README.rst

#
# This file contains the variables you'll need to pass to the role, and some
# example values.
mongopruner_pyenv_debian_packages:
  - build-essential
  - git
  - libreadline-dev
  - zlib1g-dev
  - libssl-dev
  - libbz2-dev
  - libsqlite3-dev

#mongopruner_service_name: "mongopruner-service"
mongopruner_service_user: "edx_mongopruner_worker"
mongopruner_service_home: "{{ COMMON_APP_DIR }}/mongopruner_service"
mongopruner_service_app_dir: "{{ mongopruner_service_home }}/tubular"
mongopruner_service_data_dir: "{{ COMMON_DATA_DIR }}/mongopruner_service"
mongopruner_service_log_dir: "{{ COMMON_LOG_DIR }}/mongopruner_service"
mongopruner_service_pyenv_dir: "{{ mongopruner_service_home }}/.pyenv"
mongopruner_service_user_shell: "/bin/bash"
mongopruner_service_script_path: "{{ mongopruner_service_app_dir }}/scripts"

mongopruner_service_python_version: 3.8.0
mongopruner_service_pip_version: "21.0.1"

# Set up git repos
MONGOPRUNER_SERVICE_GIT_IDENTITY: !!null
MONGOPRUNER_SERVICE_GIT_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: "tubular.git"
    VERSION: "master"
    DESTINATION: "{{ mongopruner_service_app_dir }}"
    SSH_KEY: "{{ MONGOPRUNER_SERVICE_GIT_IDENTITY }}"

# Enable the configuration of a cron job to run this periodically
MONGOPRUNER_SERVICE_ENABLE_CRON_JOB: false
MONGOPRUNER_SERVICE_CRON_JOB_HOURS: 0
MONGOPRUNER_SERVICE_CRON_JOB_MINUTES: 0
MONGOPRUNER_SERVICE_CRON_JOB_WEEKDAY: 0
