stages:
    - build

services:
    - docker:dind

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-base-image:
    stage: build
    variables:
        BASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    script:
        - docker build -t $BASE_IMAGE .
        - docker push $BASE_IMAGE
        - echo image built - $BASE_IMAGE
    only:
        - master

build-version-image:
    extends: build-base-image
    variables:
        BASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    only:
        - tags
