stages:
    - build

services:
    - docker:dind

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-base-image:
    stage: build
    variables:
        BASE_IMAGE: registry-gitlab.raccoongang.com/devops/configuration:$CI_COMMIT_REF_SLUG-develop
    script:
        - docker build -t $BASE_IMAGE .
        - docker push $BASE_IMAGE
    only:
        - master
        - ficus-rg
        - ginkgo-rg
        - hawthorn-rg

build-version-image:
    stage: build
    variables:
        BASE_IMAGE: registry-gitlab.raccoongang.com/devops/configuration:$CI_COMMIT_REF_SLUG
    script:
        - FULL_VERSION=$BASE_IMAGE
        - MINOR_VERSION=$(echo $FULL_VERSION | sed -n -e "s/\(^.*\)-.*$/\1/p")
        - MAJOR_VERSION=$(echo $MINOR_VERSION | sed -n -e "s/\(^.*\)-.*$/\1/p")
        - docker build -t $FULL_VERSION .
        - docker tag $FULL_VERSION $MINOR_VERSION
        - docker tag $FULL_VERSION $MAJOR_VERSION
        - docker push $FULL_VERSION
        - docker push $MINOR_VERSION
        - docker push $MAJOR_VERSION
    only:
        - tags
