---

- name: Create "{{ raccoongang_ssl_path }}"
  file:
    path: "{{ raccoongang_ssl_path }}"
    state: directory
    mode: 0700

- name: raccoongang ssl crt and key
  copy:
    content: "{{ item.content }}"
    dest: "{{ raccoongang_ssl_path }}/{{ item.name }}"
  with_items:
    - name: 'raccoongang-ssl.crt'
      content: "{{ raccoongang_ssl_crt }}"
    - name: 'raccoongang-ssl.key'
      content: "{{ raccoongang_ssl_key }}"
  no_log: True

- name: set lms_ssl_certificate_path fact
  set_fact:
    lms_ssl_certificate_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.crt"
    lms_ssl_certificate_key_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.key"
    cms_ssl_certificate_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.crt"
    cms_ssl_certificate_key_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.key"
    insights_ssl_certificate_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.crt"
    insights_ssl_certificate_key_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.key"
    analytics_api_ssl_certificate_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.crt"
    analytics_api_ssl_certificate_key_path: "{{ raccoongang_ssl_path }}/raccoongang-ssl.key"
