---

backup_enabled: true           # Enable the role

backup_cron: yes               # Setup cron tasks for backup
backup_cron_schedule: "11 1 * * *"

backup_user: "duplicity"
backup_runas_user: "{{ backup_user }}"    # Run backups as user

backup_home: "/etc/duplicity"             # Backup configuration directory
backup_work: "/var/duplicity"             # Working directory
backup_temp_dir: "{{ backup_work }}/tmp"
# directory to keep status files for zabbix monitoring
backup_status_dir: "/var/tmp/duplicity"

# to see available targets refer TARGET section in [README.md](../README.md)
backup_target: 'file:///var/backup'
# utility variable contains protocol part of 'backup_target'
# s3, azure, ssh, rsync, ftp, ...
backup_target_method: "{{ backup_target | regex_replace('^(.+)://.*$', '\\1') }}"

# Amazon AWS region
# if you planing to use AWS S3 in region other than default 'us-east-1'
# seting backup_aws_region is required
# backup_aws_region: 'eu-west-1'
backup_aws_region: ''

# optionally the username/password can be defined as extra variables
backup_target_user: ''
backup_target_pass: ''

backup_profiles: []
                      # see https://wiki.archlinux.org/index.php/Duply
                      # for allowed types look into templates/profiles/
                      # refer README.md for examples
                      #  - name: www
                      #    type: file
                      #    source: /var/www
                      #    exclude:
                      #      - + **.py
                      #      - - **.pyc
                      #  - name: mysql
                      #    type: mysql
                      #    source: postgresql://db_name
                      #  - name: pgsql
                      #    type: postgresql
                      #    source: postgresql://db_name

# GPG
backup_gpg_key: disabled
backup_gpg_keys_enc:
backup_gpg_key_sign:
backup_gpg_pw:
backup_gpg_opts:
backup_gpg_pw_sign:

# Time frame for old backups to keep, Used for the "purge" command.
# see duplicity man page, chapter TIME_FORMATS)
backup_max_age: 1M

# Number of full backups to keep. Used for the "purge-full" command.
# See duplicity man page, action "remove-all-but-n-full".
backup_max_full_backups: 1

# forces a full backup if last full backup reaches a specified age
backup_full_max_age: 1M

# set the size of backup chunks to VOLSIZE MB instead of the default 25MB.
backup_volsize: 250

# verbosity of output (error 0, warning 1-2, notice 3-4, info 5-8, debug 9)
backup_verbosity: 3

backup_exclude: []

backup_sys_packages:
  Ubuntu:
    common: [ "gzip", "python-boto", "cron", "build-essential", "python-dev", "librsync-dev", "virtualenv", "gettext" ]
    ftp: [ "ncftp", "lftp" ]
    ftpes: [ "ncftp", "lftp" ]
    ftps: [ "ncftp", "lftp" ]
  Ubuntu_trusty: [ "gzip", "python-boto", "cron", "build-essential", "python-dev", "librsync-dev", "python-virtualenv" ]
  CentOS:
    common: [ "gzip", "python-boto", "gcc", "python-devel", "python-virtualenv", "python-pip", "mysql-devel", "cronie", "librsync-devel", "mongodb-org-shell" ]
    ftp: [ "ncftp", "lftp" ]
    ftpes: [ "ncftp", "lftp" ]
    ftps: [ "ncftp", "lftp" ]
  Amazon:
    common: [ "gzip", "python-boto", "gcc", "python-devel", "python-virtualenv", "python-pip", "mysql-devel", "cronie", "librsync-devel", "mongodb-org-shell" ]
    ftp: [ "ncftp", "lftp" ]
    ftpes: [ "ncftp", "lftp" ]
    ftps: [ "ncftp", "lftp" ]

backup_venv: "{{ backup_home }}/.venv"
backup_venv_packages:
  common: [ "duplicity" ]
  s3: [ "boto==2.48.0", "boto3==1.4.4", "botocore==1.5.95", "s3transfer==0.1.10", "s3cmd" ]
  rsync: [ "pyrsync" ]
  sftp: [ "paramiko" ]
  ftp: [ "pyftp" ]
  azure: [ "azure==2.0.0", "azure-storage==0.20.0" ]

# https://duply.net/
# patched by RG and keeped at role files
backup_duply_template: "duply" # duply_2.0.4_rg, duply_1.9.1_rg
backup_logdir: "/var/log/duplicity"

backup_no_log: True
