---
# TODO refactoring configuration to get rid of undefined variables in ansible playbooks

backup_enabled: "{{ COMMON_ENABLE_BACKUPS_DUPLICITY }}"

backup_user: 'duplicity'
backup_duplicity:
  target: 's3://s3.amazonaws.com/backups_bucket'
  target_method: 's3'
  target_user: "{{ EDXAPP_AWS_ACCESS_KEY_ID }}"
  target_pass: "{{ EDXAPP_AWS_SECRET_ACCESS_KEY }}"

edx_backup_duplicity_profiles:
  - name: 'mysql'
    type: 'mysql'
    mysql_user: '{{ COMMON_MYSQL_READ_ONLY_USER }}'
    mysql_password: '{{ COMMON_MYSQL_READ_ONLY_PASS }}'
    mysql_host: '{{ EDXAPP_MYSQL_HOST | default("127.0.0.1") }}'

  - name: 'mongo'
    type: 'mongo'
    mongo_user: '{{ MONGO_ADMIN_USER | default("admin") }}'
    mongo_password: '{{ MONGO_ADMIN_PASSWORD }}'
    mongo_authdb: 'admin'
    mongo_host: '{{ EDXAPP_MONGO_HOSTS | default("127.0.0.1") }}'

# TODO to add AWS snapshots
# TODO to add Azure Recovery Vault
