---
COMMON_ENABLE_DISCOVERY: False

DISCOVERY_VERSION: 'open-release/hawthorn.2'

DISCOVERY_DOMAIN: 'discovery.example.com'
DISCOVERY_URL_ROOT: "{{ EDXAPP_LMS_BASE_SCHEME | default('https') }}://{{ DISCOVERY_DOMAIN }}"

DISCOVERY_MEMCACHE: "{{ EDXAPP_MEMCACHE }}"
DISCOVERY_LANGUAGE_CODE: "{{ EDXAPP_LANGUAGE_CODE }}"
DISCOVERY_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
DISCOVERY_PLATFORM_NAME: "{{ EDXAPP_PLATFORM_NAME }}"
DISCOVERY_MYSQL: "{{ mysql_host }}"

EDXAPP_JWT_AUDIENCE: "{{ COMMON_JWT_AUDIENCE }}"
EDXAPP_JWT_SECRET_KEY: "{{ COMMON_JWT_SECRET_KEY }}"
EDXAPP_LMS_ISSUER: "{{ EDXAPP_LMS_ROOT_URL }}/oauth2"

EDXAPP_COURSE_CATALOG_API_URL: "{{ DISCOVERY_URL_ROOT }}/api/v1"
