---
EDXAPP_ENABLE_EDXNOTES: "{{ COMMON_ENABLE_EDXNOTES }}"

EDX_NOTES_API_VERSION: "open-release/ironwood.2"

EDX_NOTES_RG_PUBLIC_DNS: "{{ EDXAPP_LMS_BASE }}"
EDX_NOTES_RG_PUBLIC_URI: "{{ EDXAPP_LMS_BASE_SCHEME | default('https') }}://{{ EDX_NOTES_RG_PUBLIC_DNS }}/edx_notes"
EDX_NOTES_API_MYSQL_DB_USER: "edx_notes_api"
EDX_NOTES_API_MYSQL_DB_NAME: "edx_notes_api"
EDX_NOTES_API_MYSQL_HOST: "{{ mysql_host }}"
EDXAPP_EDXNOTES_PUBLIC_API: "{{ EDX_NOTES_RG_PUBLIC_URI }}/api/v1"
EDXAPP_EDXNOTES_INTERNAL_API: "http://127.0.0.1:8120/api/v1"
EDX_NOTES_API_ELASTICSEARCH_URL: 'http://127.0.0.1:9200/'
EDX_NOTES_API_DATASTORE_NAME: 'notes'
EDX_NOTES_API_ALLOWED_HOSTS:
  - localhost
  - 127.0.0.1
  - "{{ EDX_NOTES_RG_PUBLIC_DNS }}"
