---

# TODO move/remove notifications config into separate task

slack_notification_channels:
  dev: []
  stage: []
  prod: []

# TODO refactoring to get rid of undefined variables in ansible tasks

rg_support_package: "Default"
zabbix_enabled: false
zabbix_force_in_maintenance: false

zabbix_support_conf:
  Default:
    groups:
      - "Client Prod"
    templates:
      - "Active Template OS Linux"
      - "Template App HTTPS Service"
      - "Nginx connections"
  OnSupport:
    groups:
      - "Client Prod on support"
    templates:
      - "Active Template OS Linux"
      - "Active Ubuntu reboot required"
      - "Active Template App APT Updates"
      - "Template App HTTPS Service"
      - "Active Template App EDX AD"
      - "Nginx connections"
      - "Template NMAP open ports"
  Strong:
    groups:
      - "Client Prod on support"
    templates:
      - "Active Template OS Linux"
      - "Active Ubuntu reboot required"
      - "Active Template App APT Updates"
      - "Template App HTTPS Service"
      - "Active Template App EDX AD"
      - "Active Template App Elasticsearch node"
      - "Active Template App Memcached"
      - "Active Template App MongoDB"
      - "Active Template App MySQL"
      - "Active Template App Redis"
      - "Nginx connections"
      - "Template NMAP open ports"
  VIP:
    groups:
      - "Client VIP Support"
    templates:
      - "Active Template OS Linux"
      - "Active Ubuntu reboot required"
      - "Active Template App APT Updates"
      - "Template App HTTPS Service"
      - "Active Template App EDX AD"
      - "Active Template App Elasticsearch node"
      - "Active Template App Memcached"
      - "Active Template App MongoDB"
      - "Active Template App MySQL"
      - "Active Template App Redis"
      - "Nginx connections"
      - "Template NMAP open ports"
