---
- name: create destination dir
  file:
    path: "{{ nginx_ssl_selfsigned_path }}"
    mode: 0700
    state: directory

- name: upload raccoongang selfsigned root sertificate and key
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_ssl_selfsigned_path }}/{{ item | basename }}"
    mode: 0600
  with_items:
    - "{{ nginx_ssl_selfsigned_ca }}"
    - "{{ nginx_ssl_selfsigned_cakey }}"

- name: create selfsigned extentions file
  template:
    src: selfsigned.ext.j2
    dest: "{{ nginx_ssl_selfsigned_path }}/selfsigned.ext"

- name: create key for selfsigned
  shell: >
    openssl genrsa -out {{ nginx_ssl_selfsigned_path }}/selfsigned.key 2048 ;
    chmod og-wrx {{ nginx_ssl_selfsigned_path }}/selfsigned.key

- name: create csr
  command: >
    openssl req -new -sha256 -key {{ nginx_ssl_selfsigned_path }}/selfsigned.key
    -subj '/C=US/ST=FL/O=SelfSigned, Inc./CN={{ EDXAPP_SITE_NAME }}'
    -out {{ nginx_ssl_selfsigned_path }}/selfsigned.scr

- name: generate selfsigned cert
  command: >
    openssl x509 -req -in {{ nginx_ssl_selfsigned_path }}/selfsigned.scr
    -CA {{ nginx_ssl_selfsigned_path }}/{{ nginx_ssl_selfsigned_ca | basename }}
    -CAkey {{ nginx_ssl_selfsigned_path }}/{{ nginx_ssl_selfsigned_cakey | basename }}
    -CAcreateserial
    -extfile {{ nginx_ssl_selfsigned_path }}/selfsigned.ext
    -out {{ nginx_ssl_selfsigned_path }}/selfsigned.crt
    -days {{ nginx_ssl_selfsigned_days }}
    -sha256

- name: merge cert with CA cert
  shell: "cat {{ nginx_ssl_selfsigned_path }}/{{ nginx_ssl_selfsigned_ca | basename }} >> {{ nginx_ssl_selfsigned_path }}/selfsigned.crt"

- name: add CA cert to Ubuntu's cert chain
  copy:
    src: "{{ nginx_ssl_selfsigned_path }}/{{ nginx_ssl_selfsigned_ca | basename }}"
    dest: "/usr/local/share/ca-certificates/selfsigned_ca_{{ nginx_ssl_selfsigned_ca | basename }}.crt"
    remote_src: True
    mode: 0644
  register: add_ss_ca

- name: update-ca-certificates
  command: update-ca-certificates
  when: add_ss_ca is changed

- name: remove extra files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nginx_ssl_selfsigned_path }}/selfsigned.ext"
    - "{{ nginx_ssl_selfsigned_path }}/selfsigned.scr"
    - "{{ nginx_ssl_selfsigned_path }}/{{ nginx_ssl_selfsigned_ca | basename }}"
    - "{{ nginx_ssl_selfsigned_path }}/{{ nginx_ssl_selfsigned_cakey | basename }}"

- name: set facts for certs paths
  set_fact:
    lms_ssl_certificate_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.crt"
    lms_ssl_certificate_key_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.key"
    cms_ssl_certificate_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.crt"
    cms_ssl_certificate_key_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.key"
    insights_ssl_certificate_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.crt"
    insights_ssl_certificate_key_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.key"
    analytics_api_ssl_certificate_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.crt"
    analytics_api_ssl_certificate_key_path: "{{ nginx_ssl_selfsigned_path }}/selfsigned.key"
