---

- name: restart memcached service
  systemd:
    name: "{{ MEMCACHE_SERVICE_NAME }}"
    state: restarted
    daemon_reload: yes
  listen: memcached_restart

- name: enable service
  service:
    name: "{{ MEMCACHE_SERVICE_NAME }}"
    enabled: yes
  listen: memcached_restart
